# Use the official Node.js LTS image as the base image
FROM node:18
# Create and set the working directory in the container
WORKDIR /
# Copy the rest of the application code to the container
COPY . .
# Copy package.json and package-lock.json to the container
COPY package.json .
COPY package-lock.json .
COPY didpass-verifier-sdk-0.1.1-beta.2.tgz .
COPY didpass-zkpass-client-ts-0.1.0-beta.2.tgz .
# Install dependencies
RUN npm install
# Expose the port the app runs on
EXPOSE 3002