[package]
name = "zkpass-ws"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zkpass-core = { path = "../zkpass-core" }
zkpass-svc-common = { path = "../zkpass-svc-common" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.97"
clap = "3.2"
actix-web = "4.5.1"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
amqprs = "1.5.1"
lazy_static = "1.4.0"
dotenvy = "0.15.7"
base64 = "0.21.4"
mysql = "24.0.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
futures = "0.3"
fluent = "0.16.0"
fluent-langneg = "0.13.0"
unic-langid = "0.9.0"
openssl = "0.10.64"
aws-config = { version = "1.1.6", features = ["behavior-version-latest"] }
aws-sdk-kms = "1.3.0"
aws-sdk-sts = "1.10.0"
semver = "1.0"

[target.'cfg(target_os = "linux")'.dependencies]
vsock = "0.5.0"

[dev-dependencies]
httpmock = "0.6.8"
serial_test = "3.0.0"
