services:
  control-panel:
    image: asia.gcr.io/gdp-labs/zkpass/control-panel:SHORT_SHA
    ports:
      - "3000:3000"
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    restart: on-failure:5
    mem_limit: ${MEM_LIMIT:-8g}
    healthcheck:
      test: curl -o /dev/null -s -w '%{http_code}' http://localhost:3000/
      start_period: 120s
      timeout: 3s
      retries: 10
    env_file:
      - zkpass.env

