[package]
name = "zkpass-query"
version = "1.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.99"
jmespath = "0.3.0"
unicase = "2.7.0"
tracing = "0.1.40"
zkpass-query-types = { version = "1.0.0", path = "../../zkpass-query/types" }
paste = "1.0.14"
