[workspace]
[package]
version = "1.3.0"
name = "sp1-zkpass-query-method"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git" }
serde = "1.0.197"
serde_derive = "1.0.197"
serde_json = "1.0.114"
zkpass-query = { path = "../../core" }
