[package]
name = "r0-zkpass-query-guest"
version = "1.5.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.0", default-features = false, features = ['std'] }
zkpass-query = { path = "../../../core" }
postcard = "1.0"
