[package]
name = "r0-zkpass-query-guest"
version = "1.3.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.2", default-features = false, features = ['std'] }
zkpass-query = { path = "../../../core" }
postcard = "1.0"
