[package]
name = "zkpass-query-types"
version = "0.3.0-rc.1"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.99"
jmespath = "0.3.0"
unicase = "2.7.0"
chrono = "0.4.37"
